Task 4 Hvisevich
MikitaTsiarentsyeu/MRTI2920 pull request #41
Opened 2020-08-23 11:01 UTC by Vitaly-Khvisevich

This is my decision task №4

2020-08-24 12:25 UTC, MikitaTsiarentsyeu requested changes
Please implement another approach that will leave the initial list intact.

2020-08-24 12:25 UTC, MikitaTsiarentsyeu commented on Tasks/Task4/Hvisevich
> +            S[i]=Summa(S[i])
Are you aware that you basically destroyed the list structure by such a assignments?

2020-08-24 19:47 UTC, Vitaly-Khvisevich commented
changed the text in the code check please

2020-08-26 08:18 UTC, MikitaTsiarentsyeu approved these changes
it's good enough now, your score is 9.0

2020-08-26 08:18 UTC, merged